version: "3.7"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: "grafana/grafana"
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
    privileged: true

  loki:
    image: "grafana/loki"
    user: "${UID}:${GID}"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yml:/mnt/config/loki-config.yml
      - ./loki:/loki
    restart: always
    command: '--config.file=/mnt/config/loki-config.yml'
